const getFineArtCatalogue = () => {
  const catalogue = [
    {
      title: "Family Photos",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/family-photos.jpg",
      avail: false,
      price: 95000,
      createdTimeStamp: "2021-04-11 11:00:00",
      medium: "Oil on Canvas",
      size: "40cm x 50cm",
      show: true,
    },
    {
      title: "Kindling",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/kindling.jpg",
      avail: false,
      price: 95000,
      createdTimeStamp: "2021-02-09 11:00:00",
      medium: "Oil on Canvas",
      size: "40cm x 50cm",
      show: true,
    },
    {
      title: "Movable (At The Door)",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/Movable.jpg",
      avail: false,
      price: 95000,
      createdTimeStamp: "2022-01-01 11:00:00",
      medium: "Oil on Canvas",
      size: "40cm x 50cm",
      show: true,
    },
    {
      title: "Potassium",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/potassium.jpg",
      avail: false,
      price: 95000,
      createdTimeStamp: "2022-07-01 11:00:00",
      medium: "Oil on Canvas",
      size: "40cm x 50cm",
      show: true,
    },
    {
      title: "Sofa",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/sofa.jpg",
      avail: false,
      price: 95000,
      createdTimeStamp: "2021-9-5 11:00:00",
      medium: "Oil on Canvas",
      size: "40cm x 50cm",
      show: true,
    },
    {
      title: "We're Planning On Letting The Plants Take Over",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/plants-take-over.jpg",
      avail: true,
      price: 95000,
      createdTimeStamp: "2022-9-5 11:00:00",
      medium: "Oil on Canvas",
      size: "40cm x 50cm",
      show: true,
    },
    {
      title: "Backbones",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/backbones.jpg",
      avail: false,
      price: 95000,
      createdTimeStamp: "2022-6-5 11:00:00",
      medium: "Oil on Canvas",
      size: "40cm x 50cm",
      show: true,
    },
    {
      title: "Inside",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/inside.jpg",
      avail: true,
      price: 120000,
      createdTimeStamp: "2021-02-10 11:00:00",
      medium: "Oil on Canvas",
      size: "50cm x 60cm",
      show: true,
    },
    {
      title: "A Colourful Outlook",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/a-colourful-outlook.jpg",
      avail: true,
      price: 160000,
      createdTimeStamp: "2020-05-13 11:00:00",
      medium: "Oil on Canvas",
      size: "50cm x 75cm",
      show: true,
    },
    {
      title: "A.M",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/am.jpg",
      avail: false,
      price: 160000,
      createdTimeStamp: "2021-05-13 11:00:00",
      medium: "Oil on Canvas",
      size: "50cm x 75cm",
      show: true,
    },
    {
      title: "I'd Like To Tile My House With Books",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/tile-my-house-with-books.jpg",
      avail: true,
      price: 160000,
      createdTimeStamp: "2021-11-1 11:00:00",
      medium: "Oil on Canvas",
      size: "50cm x 75cm",
      show: true,
    },
    {
      title: "Knowledge and Nature (no 2)",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/knowledgeAndNature.jpg",
      avail: false,
      price: 210000,
      createdTimeStamp: "2021-06-28 11:00:00",
      medium: "Oil on Canvas",
      size: "120cm x 60cm",
      show: true,
    },
    {
      title: "Timeless",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/timeless.jpg",
      avail: true,
      price: 160000,
      createdTimeStamp: "2022-11-1 11:00:00",
      medium: "Oil on Canvas",
      size: "50cm x 75cm",
      show: true,
    },
    {
      title: "Orange Peel",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/orangePeel.jpg",
      avail: true,
      price: 180000,
      createdTimeStamp: "2021-11-5 11:00:00",
      medium: "Oil on Canvas",
      size: "60cm x 60cm",
      show: true,
    },
    {
      title: "Plants and Planets",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/plantsAndPlanets.jpg",
      avail: true,
      price: 195000,
      createdTimeStamp: "2021-10-2 11:00:00",
      medium: "Oil on Canvas",
      size: "75cm x 75cm",
      show: true,
    },
    {
      title: "Green Energy",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/green-energy.jpg",
      avail: true,
      price: 285000,
      createdTimeStamp: "2021-10-2 11:00:00",
      medium: "Oil on Canvas",
      size: "152cm x 122cm",
      show: true,
    },
    {
      title: "Quiet",
      desc: "Part of the collection from the 'Hung Drawn and painted' exhibition",
      image: "/large/quiet.jpg",
      avail: true,
      price: 285000,
      createdTimeStamp: "2021-10-2 11:00:00",
      medium: "Oil on Canvas",
      size: "150cm x 100cm",
      show: true,
    },
    {
      title: "Drawn Up",
      desc: "New work, 2023",
      image: "/large/drawnUp.jpg",
      avail: true,
      price: 160000,
      createdTimeStamp: "2022-11-1 11:00:00",
      medium: "Oil on Canvas",
      size: "50cm x 75cm",
      show: true,
    },
    {
      title: "Shelf Life",
      desc: "New work, 2023",
      image: "/large/shelflife.jpg",
      avail: true,
      price: 160000,
      createdTimeStamp: "2022-02-5 11:00:00",
      medium: "Oil on Canvas",
      size: "50cm x 75cm",
      show: true,
    },
    {
      title: "Fusion",
      desc: "New work, 2023",
      image: "large/fusion.jpg",
      avail: true,
      price: 160000,
      createdTimeStamp: "2022-02-5 11:00:00",
      medium: "Oil on Canvas",
      size: "50cm x 75cm",
      show: true,
    },
  ];
  catalogue.forEach((item, index) => {
    item.id = index + 1;
  });
  return catalogue;
};

export default getFineArtCatalogue;

//for list of images
// images: [
//   "src/assets/images/fineArt/large/orangePeel.jpg",
//   "src/assets/images/fineArt/small/orangePeelSmall.jpg",
// ],
