const illustrationCatalogue = [
  {
    id: "Suffolk Mind Emotional Needs",
    title: "Suffolk Mind",
    desc: "Suffolk Mind Commission",
    images: [
      "src/assets/images/illustration/large/suffolkMind/Suffolk Mind 2021 Resources Black and White Thinking Fight or Flight Hutch.jpg",
      "src/assets/images/illustration/large/suffolkMind/Suffolk Mind 2021 Resources Dreaming Am I Dre m ng Hutch.jpg",
      "src/assets/images/illustration/large/suffolkMind/Suffolk Mind 2021 Resources Emotions E Motion Hutch.jpg",
      "src/assets/images/illustration/large/suffolkMind/Suffolk Mind 2021 Resources Imagination Imagine Nation Hutch.jpg",
      "src/assets/images/illustration/large/suffolkMind/Suffolk Mind 2021 Resources Memory Memory Garden Hutch.jpg",
      "src/assets/images/illustration/large/suffolkMind/Suffolk Mind 2021 Resources Mini Card Layout Hutch.jpg",
      "src/assets/images/illustration/large/suffolkMind/Suffolk Mind 2021 Resources Observing Self Making Good Hutch.jpg",
      "src/assets/images/illustration/large/suffolkMind/Suffolk Mind 2021 Resources Pattern Matching Snap Linden Hutch.jpg",
      "src/assets/images/illustration/large/suffolkMind/Suffolk Mind 2021 Resources Rapport Rap Port Hutch.jpg",
      "src/assets/images/illustration/large/suffolkMind/Suffolk Mind 2021 Resources Rational Thinking Rach's Nail Tinkering Hutch.jpg",
    ],
    createdTimeStamp: "2021-05-13 11:00:00",
    medium: "pen and goashe",
  },
  {
    id: "Obsidian Wine Co.",
    title: "Obsidian Wine Co. Label Design",
    desc: "Obsidian Wine Commission",
    images: [
      "src/assets/images/illustration/large/obsidian/Hutch 12 Obsidian Wine.jpg",
      "src/assets/images/illustration/large/obsidian/OBSIDIAN.jpeg",
      "src/assets/images/illustration/large/obsidian/ORCHF17_webstore-(1).png",
      "src/assets/images/illustration/large/obsidian/ORSB18_webstore-(1).png",
      "src/assets/images/illustration/large/obsidian/PERUVIAN.jpeg",
    ],
    createdTimeStamp: "2020-05-13 11:00:00",
    medium: "pen on acid free paper",
  },
  {
    id: "Insights Publication",
    title: "Insights Publication 2018",
    desc: "Insights Publication 2018 Commission",
    images: [
      "src/assets/images/illustration/large/insights/Insights 2021 Back Cover artwork only no titles Hutch.jpg",
      "src/assets/images/illustration/large/insights/Insights 2021 Employment Centre HGV Hutch.jpg",
      "src/assets/images/illustration/large/insights/Insights 2021 Employment Left Plumber and 3 other workers Hutch.jpg",
      "src/assets/images/illustration/large/insights/Insights 2021 Employment Right Shopworker and 5 other workers Hutch.jpg",
      "src/assets/images/illustration/large/insights/Insights 2021 Family and Conenction Right Hutch.jpg",
      "src/assets/images/illustration/large/insights/Insights 2021 Family and Conenction Right Hutch.jpg",
      "src/assets/images/illustration/large/insights/Insights 2021 Foodbank Hutch.jpg",
      "src/assets/images/illustration/large/insights/Insights 2021 Front Cover artwork only no titles Hutch.jpg",
      "src/assets/images/illustration/large/insights/Insights 2021 Income, Consumption and Wealth Right Hutch.jpg",
      "src/assets/images/illustration/large/insights/Insights 2021 Polling Station Hutch.jpg",
      "src/assets/images/illustration/large/insights/Insights 2021 Youth Strike Hutch.jpg",
      "src/assets/images/illustration/large/insights/Page 28 mini illo.jpg",
    ],
    createdTimeStamp: "2018-05-13 11:00:00",
    medium: "pen on acid free paper",
  },
];

export default illustrationCatalogue;
